main: cc.carm.plugin.playerprefix.Main

name: ${project.name}
version: ${project.version}
description: ${project.description}
author: CarmJos
website: ${project.url}

depend:
  - ProtocolLib
softdepend:
  - PlaceholderAPI

commands:
  PlayerPrefix:
    aliases:
      - prefix


