main: cc.carm.plugin.playerprefix.Main

name: ${project.artifactId}
version: ${project.version}

depend:
  - ProtocolLib
softdepend:
  - PlaceholderAPI

commands:
  PlayerPrefix:
    aliases:
      - prefix

author: CarmJos
website: ${project.url}
description: ${project.description}
